import { makeStyles } from "@material-ui/core/styles";
export default makeStyles((theme)=>({
    media:{
        borderRadius:'20px',
        objectFit:'cover',
        widht:'100%',
        maxHeight:'600px',
    },
    card:{
        display:'flex',
        width:'100%',
        [theme.breakpoints.down('sm')]:{
            flexWrap:'wrap',
            flexDirection:'column',
        },

    },
    section:{
        borderRadius:'20px',
        margin:'10px',
        flex:'1'
    },
    imageSection:{
        marginLeft:'20px',
        [theme.breakpoints.down('sm')]:{
            marginLeft:0,
        },
    },
    recomendedPosts:{
        display:'flex',
        [theme.breakpoints.down('sm')]:{
            flexDirection:'column',
        }
    },
    commentsOuterContainer:{
        display:'flex',
        justifyContent:'space-between',
    },
    commentsInnerContainer:{
        height:'200px',
        overflow:'auto',
        margin:'30px',
    }
}))